services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: devops-project-1-app:latest
    expose:
      - "5000"   # only to the internal compose network
    healthcheck:
      # Use Python (already in the image) to call /health
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:5000/health').status==200 else 1)\""]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - app_net

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "8080:80"     # host:container — visit http://localhost:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
