name: Project 2 — CI (tests only)

on:
  push:
    branches: ['**']
    paths:
      - 'devops-project-2/**'
      - '.github/workflows/project2-ci.yml'
  pull_request:
    paths:
      - 'devops-project-2/**'
      - '.github/workflows/project2-ci.yml'

permissions:
  contents: read

# Run all shell steps from the Project 2 folder
defaults:
  run:
    working-directory: devops-project-2

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest

      - name: Run unit tests
        run: pytest -q

